###recuperar total de gastado o ingresado
  http://localhost:1234/transacciones/type/balance/67301d67c4e28e2952f30712/ingreso

###recuperar transacciones por tipo o todas[ingreso,gasto, mixed (todas)]
http://localhost:1234/transacciones/all/67301d67c4e28e2952f30712/mixed

### Recuperar total ahorradocon id de usuario
GET http://localhost:1234/transacciones/balance/67301d67c4e28e2952f30712

### Recuperar una transaccion especifico con id
GET http://localhost:1234/transacciones/67305ec92d064f7a9bd5fdcf

### Borrado logico una transaccion por id
DELETE http://localhost:1234/transacciones/6730e884d2a7e5bdc91a51bd

### Recuperar todas las películas por un género
GET http://localhost:1234/usuarios

### Crear una transaccion con POST
POST http://localhost:1234/transacciones
Content-Type: application/json

{
  "usuario_id": "6740338c619e791515750c3a",
  "monto": 5000,
  "tipo": "ingreso",
  "descripcion": "Pago poooor servicios",
  "imagen": [
    "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAA...",
    "data:image/jpeg;base64,aBcdEfGhIjKlMnOpQrSt..."
  ]
}

### Actualizar una transaccion
PATCH http://localhost:1234/transacciones/674bf8fc328f59506b697a7e
Content-Type: application/json

{
  "monto": 9,
  "tipo": "ingreso",
  "descripcion": "test test",
  "imagen": [
    "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAA...",
    "data:image/jpeg;base64,aBcdEfGhIjKlMnOpQrSt..."
  ]
}

### lastest transac
POST http://localhost:1234/transacciones/last
Content-Type: application/json

{
  "id": "67301d67c4e28e2952f30712"
}